#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx prettier --write .
npm run lint
npm run ci-test

# Auto generate and stage bundle
npm run bundle
git add dist

docker run --rm --volume "$(git rev-parse --show-toplevel)":/src ghcr.io/zricethezav/gitleaks:latest protect --source /src --verbose --redact --staged
