name: vet OSS Components

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write
  pull-requests: write
  security-events: write

jobs:
  vet:
    name: vet
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Run vet
        id: vet
        uses: ./
        with:
          cloud: true
          cloud-key: ${{ secrets.SAFEDEP_CLOUD_API_KEY }}
          cloud-tenant: ${{ secrets.SAFEDEP_CLOUD_TENANT_DOMAIN }}
          enable-comments-proxy: true
          trusted-registries: |
            https://registry.npmjs.org/strip-ansi
            https://registry.npmjs.org/string-width
            https://registry.npmjs.org/wrap-ansi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: ${{ steps.vet.outputs.report != '' }}
        with:
          sarif_file: ${{ steps.vet.outputs.report }}
          category: vet
